spring:
  profiles: production
  datasource:
    url: jdbc:mariadb://localhost:3306/findSatoshi
    username: findSatoshi
    password: findSatoshi
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: validate #create-drop
  flyway:
    enabled: true
    baselineOnMigrate: true
server:
  port: 8080
  servlet:
    context-path: /findSatoshi	
logging:
  level:
    root: INFO
---

spring:
  profiles: docker
  datasource:
    url: jdbc:mariadb://db:3306/findSatoshi
    username: findSatoshi
    password: findSatoshi
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
  flyway:
    enabled: true
    baselineOnMigrate: true
server:
  port: 8080
  servlet:
    context-path: /findSatoshi	
logging:
  level:
    root: INFO
---

spring:
  profiles: development
  datasource:
    url: jdbc:mariadb://172.21.101.178:3306/findSatoshi
    username: findSatoshi
    password: findSatoshi
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop #validate #create-drop #validate 
  flyway:
    enabled: false
    baselineOnMigrate: false
server:
  port: 8080
  servlet:
    context-path: /findSatoshi	
logging:
  level:
    root: DEBUG