spring:
  profiles: docker
  datasource:
    url: jdbc:mariadb://127.0.0.1:3306/findSatoshi
    username: findSatoshi
    password: findSatoshi
    driver-class-name: org.mariadb.jdbc.Driver
    initialization-mode: always
  jpa:
    hibernate:
      ddl-auto: create-drop
  flyway:
    enabled: true
    baselineOnMigrate: true
server:
  port: 8080
  servlet:
    context-path: /findSatoshi	
logging:
  level:
    root: DEBUG
find-satoshi:
  url: http://e59c9cea.ngrok.io
---

spring:
  profiles: development
  datasource:
    url: jdbc:mariadb://localhost:3306/findSatoshi
    username: findSatoshi
    password: findSatoshi
    driver-class-name: org.mariadb.jdbc.Driver
    initialization-mode: always
  jpa:
    hibernate:
      ddl-auto: create-drop #validate #create-drop #validate 
  flyway:
    enabled: false
    baselineOnMigrate: false
server:
  port: 8081
  servlet:
    context-path: /findSatoshi
logging:
  level:
    root: DEBUG
find-satoshi:
  url: http://bb7146414466.ngrok.io/
  success-url: localhost:4200
  open-node: b95d29ac-4ce9-45c9-ab9e-8767b35a01de
